Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2019-03, with the labels that each got.

#2 Add OWNERS
  OWNERS
Labels: size/S

#5 Pull in latest changes from upstream repo
  Gopkg.lock
  pkg/cloud/baremetal/actuators/machine/actuator.go
  vendor/github.com/metalkube/baremetal-operator/Gopkg.lock
  vendor/github.com/metalkube/baremetal-operator/Gopkg.toml
  vendor/github.com/metalkube/baremetal-operator/Makefile
  vendor/github.com/metalkube/baremetal-operator/README.md
  vendor/github.com/metalkube/baremetal-operator/build/Dockerfile
  vendor/github.com/metalkube/baremetal-operator/deploy/crds/metalkube_v1alpha1_baremetalhost_cr.yaml
  vendor/github.com/metalkube/baremetal-operator/deploy/crds/worker-0.yaml
  vendor/github.com/metalkube/baremetal-operator/deploy/operator.yaml
  vendor/github.com/metalkube/baremetal-operator/docs/api.md
  vendor/github.com/metalkube/baremetal-operator/docs/dev-setup.md
  vendor/github.com/metalkube/baremetal-operator/docs/publishing-images.md
  vendor/github.com/metalkube/baremetal-operator/pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
  vendor/github.com/metalkube/baremetal-operator/pkg/apis/metalkube/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metalkube/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metalkube/baremetal-operator/pkg/bmc/credentials.go
  vendor/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/fixture/fixture.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/ironic/ironic.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/provisioner.go
Labels: lgtm, size/XXL

#6 OWNERS: Add Steve Hardy.
  OWNERS
Labels: approved, lgtm, size/XS

#7 Sync with upstream
  .travis.yml
  CONTRIBUTING.md
  DCO
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  cmd/manager/main.go
  docs/dev/minikube.md
  docs/dev/openshift.md
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
  tools/install_kustomize.sh
  vendor/github.com/go-log/log/LICENSE
  vendor/github.com/go-log/log/README.md
  vendor/github.com/go-log/log/capture/capture.go
  vendor/github.com/go-log/log/fmt/fmt.go
  vendor/github.com/go-log/log/info/info.go
  vendor/github.com/go-log/log/log.go
  vendor/github.com/go-log/log/log/log.go
  vendor/github.com/go-log/log/nest/nest.go
  vendor/github.com/go-log/log/print/print.go
  vendor/github.com/metalkube/baremetal-operator/.travis.yml
  vendor/github.com/metalkube/baremetal-operator/CONTRIBUTING.md
  vendor/github.com/metalkube/baremetal-operator/DCO
  vendor/github.com/metalkube/baremetal-operator/Gopkg.lock
  vendor/github.com/metalkube/baremetal-operator/Gopkg.toml
  vendor/github.com/metalkube/baremetal-operator/Makefile
  vendor/github.com/metalkube/baremetal-operator/README.md
  vendor/github.com/metalkube/baremetal-operator/cmd/make-worker/main.go
  vendor/github.com/metalkube/baremetal-operator/deploy/crds/worker-0.yaml
  vendor/github.com/metalkube/baremetal-operator/docs/dev-setup.md
  vendor/github.com/metalkube/baremetal-operator/pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
  vendor/github.com/metalkube/baremetal-operator/pkg/apis/metalkube/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metalkube/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metalkube/baremetal-operator/pkg/bmc/credentials.go
  vendor/github.com/metalkube/baremetal-operator/pkg/bmc/ipmi.go
  vendor/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/fixture/fixture.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/ironic/ironic.go
  vendor/github.com/metalkube/baremetal-operator/pkg/provisioner/provisioner.go
  vendor/github.com/metalkube/baremetal-operator/pkg/utils/stringlist.go
  vendor/github.com/openshift/cluster-api/Dockerfile
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Makefile
  vendor/github.com/openshift/cluster-api/config/kustomization.yaml
  vendor/github.com/openshift/cluster-api/hack/verify_history.sh
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/doc.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/register.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/consts.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/register.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/errors/machines.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/XXL
