Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2019-07, with the labels that each got.

#32 ensure we pull the baremetal-operator code from the openshift fork
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/metal3-io/baremetal-operator/Dockerfile
  vendor/github.com/metal3-io/baremetal-operator/OWNERS
Labels: approved, lgtm, size/S

#33 Fix import for runtime.Scheme
  pkg/apis/baremetal/v1alpha1/register.go
Labels: approved, lgtm, size/XS

#34 pull from upstream
  Gopkg.lock
  cmd/manager/main.go
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
  pkg/manager/wrapper/mapper.go
  pkg/manager/wrapper/mapper_test.go
  pkg/manager/wrapper/wrapper.go
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.toml
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_node_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_node_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_creation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_creation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_creation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_creation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_deletion.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_deletion.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/node_controller.md
  vendor/sigs.k8s.io/cluster-api/docs/proposals/20181121-machine-api.md
  vendor/sigs.k8s.io/cluster-api/docs/proposals/YYYYMMDD-template.md
  vendor/sigs.k8s.io/cluster-api/docs/scope-and-objectives.md
  vendor/sigs.k8s.io/cluster-api/docs/staging-use-cases.md
  vendor/sigs.k8s.io/cluster-api/hack/sed.sh
  vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
  vendor/sigs.k8s.io/cluster-api/logos/README.md
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_1.pdf
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_2.pdf
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_final-01.svg
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_final-02.svg
Labels: approved, lgtm, size/XXL

#35 Openshift pull downstream 20190702
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/L

#36 update bmo 20190708
  vendor/github.com/metal3-io/baremetal-operator/Makefile
  vendor/github.com/metal3-io/baremetal-operator/build/Dockerfile
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/main.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/templates/templates.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-virt-host/main.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/manager/main.go
  vendor/github.com/metal3-io/baremetal-operator/deploy/crds/demo-hosts.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
  vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.dot
  vendor/github.com/metal3-io/baremetal-operator/docs/api.md
  vendor/github.com/metal3-io/baremetal-operator/docs/dev-setup.md
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#37 pull upstream 20190712
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.lock
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.toml
  vendor/github.com/metal3-io/baremetal-operator/README.md
  vendor/github.com/metal3-io/baremetal-operator/cmd/manager/main.go
  vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.dot
  vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.png
  vendor/github.com/metal3-io/baremetal-operator/docs/api.md
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/version/version.go
Labels: approved, lgtm, size/L

#38 update vendored cluster-api and kubernetes-drain
  Gopkg.lock
  vendor/github.com/metal3-io/baremetal-operator/Dockerfile
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.lock
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.toml
  vendor/github.com/metal3-io/baremetal-operator/Makefile
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-virt-host/main.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/manager/main.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
  vendor/github.com/openshift/kubernetes-drain/drain.go
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_node_reconciliation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/activity_node_reconciliation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_creation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_creation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_creation.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_creation.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_deletion.drawio
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/images/sequence_machine_deletion.svg
  vendor/sigs.k8s.io/cluster-api/docs/book/common_code/node_controller.md
  vendor/sigs.k8s.io/cluster-api/docs/proposals/20181121-machine-api.md
  vendor/sigs.k8s.io/cluster-api/docs/proposals/YYYYMMDD-template.md
  vendor/sigs.k8s.io/cluster-api/docs/scope-and-objectives.md
  vendor/sigs.k8s.io/cluster-api/docs/staging-use-cases.md
  vendor/sigs.k8s.io/cluster-api/hack/sed.sh
  vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
  vendor/sigs.k8s.io/cluster-api/logos/README.md
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_1.pdf
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_2.pdf
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_final-01.svg
  vendor/sigs.k8s.io/cluster-api/logos/kubernetes-cluster-logos_final-02.svg
Labels: approved, lgtm, size/XL

#40 Set NodeInternalDNS address on Machine.
  pkg/cloud/baremetal/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS
