Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2020-08, with the labels that each got.

#94 Bug 1862875: remove machine finalizer from host when deleting machine
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#98 add zaneb as reviwer and approver
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#97 Bug 1869318: Remove finalizer from Node on delete
  pkg/cloud/baremetal/actuators/machine/actuator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#102 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#100 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
