Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2020-09, with the labels that each got.

#107 Bug 1874618: add a make target to run only the unit tests
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#106 Bug 1864352: Update leader election for release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#110 Bug 1878293: Unpin controller-runtime
  go.mod
  go.sum
  pkg/manager/wrapper/wrapper.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#108 Bug 1874618: add hack scripts to install dependencies for unit tests
  hack/ci-test.sh
  hack/fetch_ext_bins.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#111 Bug 1874618: fix unit tests so we can add a CI job
  go.mod
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#112 Bug 1845607:Add generate-check Makefile target to check the generated code and CRDs
  Makefile
  config/baremetal.cluster.k8s.io_baremetalmachineproviderspecs.yaml
  config/baremetal.cluster.k8s.io_baremetalmachineproviderstatuses.yaml
  config/crds/baremetal.cluster.k8s.io_baremetalmachineproviderspecs.yaml
  config/crds/baremetal.cluster.k8s.io_baremetalmachineproviderstatuses.yaml
  hack/generate.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#114 Bug 1879284: Handle StateAvailable
  pkg/cloud/baremetal/actuators/machine/actuator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#116 Bug 1878880: re-vendor machine-api-operator at e0db6b65
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/Dockerfile.rhel
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
