Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2020-03, with the labels that each got.

#52 adds auto-scaling for MachineSet based on number of BareMetalHosts
  Gopkg.lock
  README.md
  cmd/manager/main.go
  config/rbac/rbac_role.yaml
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
  pkg/controller/add_machineset.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/machineset/mapper.go
  pkg/controller/machineset/mapper_test.go
Labels: approved, lgtm, size/XL

#55 Enable leader election
  cmd/manager/main.go
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#54 Update kustomize to v3.5.4 to fix issue with "make test"
  tools/install_kustomize.sh
Labels: approved, lgtm, size/XS

#58 updates controller-runtime to v0.2.2
  Gopkg.lock
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/mapper.go
  vendor/sigs.k8s.io/controller-runtime/.travis.yml
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/Gopkg.lock
  vendor/sigs.k8s.io/controller-runtime/TMP-LOGGING.md
  vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/examples/README.md
  vendor/sigs.k8s.io/controller-runtime/examples/builtins/controller.go
  vendor/sigs.k8s.io/controller-runtime/examples/builtins/main.go
  vendor/sigs.k8s.io/controller-runtime/examples/crd/pkg/resource.go
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/hack/check-everything.sh
  vendor/sigs.k8s.io/controller-runtime/hack/ci-check-everything.sh
  vendor/sigs.k8s.io/controller-runtime/hack/release/release-notes.sh
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/recorder/recorder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go
  vendor/sigs.k8s.io/controller-runtime/pkg/patterns/application/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/decode.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher/certwatcher.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, lgtm, vendor-update

#60 complete forking of openshift version from metal3 verison
  Dockerfile
  Makefile
  PROJECT
  cmd/manager/main.go
  config/default/manager_image_patch.yaml
  pkg/apis/addtoscheme_baremetal_v1alpha1.go
  pkg/apis/baremetal/v1alpha1/doc.go
  pkg/apis/baremetal/v1alpha1/register.go
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
  pkg/controller/add_machineset.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/machineset/mapper.go
  pkg/controller/machineset/mapper_test.go
Labels: approved, lgtm

#61 Fixing error handling
  pkg/cloud/baremetal/actuators/machine/actuator.go
Labels: approved, lgtm, needs-ok-to-test

#44 docs/api: Fix curly quotes in YAML examples
  docs/api.md
Labels: approved, lgtm, size/XS
