Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2020-02, with the labels that each got.

#49 Bug 1804408: update vendored copy of baremetal-operator
  Gopkg.lock
  pkg/cloud/baremetal/actuators/machine/actuator.go
  vendor/github.com/metal3-io/baremetal-operator/.travis.yml
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.lock
  vendor/github.com/metal3-io/baremetal-operator/Gopkg.toml
  vendor/github.com/metal3-io/baremetal-operator/Makefile
  vendor/github.com/metal3-io/baremetal-operator/README.md
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/main.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/make-bm-worker/templates/templates.go
  vendor/github.com/metal3-io/baremetal-operator/cmd/manager/main.go
  vendor/github.com/metal3-io/baremetal-operator/deploy/crds/metal3.io_baremetalhosts_crd.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/ironic_bmo_configmap.env
  vendor/github.com/metal3-io/baremetal-operator/deploy/ironic_bmo_configmap.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/ironic_ci.env
  vendor/github.com/metal3-io/baremetal-operator/deploy/kustomization.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/namespace.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/operator_ironic.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/role.yaml
  vendor/github.com/metal3-io/baremetal-operator/deploy/role_binding.yaml
  vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.dot
  vendor/github.com/metal3-io/baremetal-operator/docs/BaremetalHost_ProvisioningState.png
  vendor/github.com/metal3-io/baremetal-operator/docs/api.md
  vendor/github.com/metal3-io/baremetal-operator/docs/baremetalhost-states.md
  vendor/github.com/metal3-io/baremetal-operator/docs/dev-setup.md
  vendor/github.com/metal3-io/baremetal-operator/docs/publishing-images.md
  vendor/github.com/metal3-io/baremetal-operator/docs/testing.md
  vendor/github.com/metal3-io/baremetal-operator/examples/demo-hosts.yaml
  vendor/github.com/metal3-io/baremetal-operator/examples/example-host-bad-credentials.yaml
  vendor/github.com/metal3-io/baremetal-operator/examples/example-host.yaml
  vendor/github.com/metal3-io/baremetal-operator/examples/worker-0.yaml
  vendor/github.com/metal3-io/baremetal-operator/hack/gofmt.sh
  vendor/github.com/metal3-io/baremetal-operator/hack/gosec.sh
  vendor/github.com/metal3-io/baremetal-operator/hack/govet.sh
  vendor/github.com/metal3-io/baremetal-operator/hack/markdownlint.sh
  vendor/github.com/metal3-io/baremetal-operator/hack/shellcheck.sh
  vendor/github.com/metal3-io/baremetal-operator/hack/unit.sh
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/zz_generated.openapi.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/action_result.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/metrics.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go
  vendor/github.com/metal3-io/baremetal-operator/tools/clean_host.sh
  vendor/github.com/metal3-io/baremetal-operator/tools/run_local_ironic.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#50 fixes broken `make manifests`, which was also breaking `make unit`.
  Makefile
Labels: approved, lgtm, size/XS

#51 Delete Machine when BareMetalHost is deleted
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/L
