Repository openshift/cluster-api-provider-baremetal, pull requests merged in 2021-03, with the labels that each got.

#140 stop generating CRDs for provider spec and status
  Makefile
  config/crds/baremetal.cluster.k8s.io_baremetalmachineproviderspecs.yaml
  config/crds/baremetal.cluster.k8s.io_baremetalmachineproviderstatuses.yaml
  hack/generate.sh
  pkg/apis/baremetal/v1alpha1/baremetalmachineproviderspec_types.go
  pkg/apis/baremetal/v1alpha1/baremetalmachineproviderspec_types_test.go
  pkg/apis/baremetal/v1alpha1/baremetalmachineproviderstatus_types.go
  pkg/apis/baremetal/v1alpha1/baremetalmachineproviderstatus_types_test.go
Labels: approved, lgtm

#137 "Bug 1912531: revendor mao"
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/go.mod
  vendor/github.com/openshift/machine-api-operator/go.sum
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#141 add stbenjam to owners file
  OWNERS
Labels: approved, lgtm

#142 Bug 1857008: Set the machine instance state annotation
  pkg/cloud/baremetal/actuators/machine/actuator.go
  pkg/cloud/baremetal/actuators/machine/actuator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
